version: '3.3'
services:
    speedtest:
        restart: unless-stopped
        container_name: openspeedtest
        ports:
            - '3000:3000' #HTTP
            - '3001:3001' #HTTPS
        image: openspeedtest/latest